### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by franchb** [franchb/go-sqlite3#2]
- [ ] use [zstd-seekable-format-go](https://github.com/SaveTheRbtz/zstd-seekable-format-go) with the [reader VFS](https://pkg.go.dev/github.com/ncruces/go-sqlite3/vfs/readervfs). https://github.com/ncruces/go-sqlite3/issues/105
- [ ] benchmark [Integrated assembler improvements in LLVM 19 ](https://maskray.me/blog/2024-06-30-integrated-assembler-improvements-in-llvm-19)
- [ ] experiment with PGO in WASM https://sqlite.org/forum/forumpost/7ce7a5f03d  and https://github.com/zamazan4ik/awesome-pgo/blob/main/sqlite.md
